// stage 2/vue implementaion/src/pages/TicketsPage.vue
<script setup>
import { ref, computed } from "vue";
import { useRouter } from "vue-router";
import { useToast } from "vue-toastification";
import { useTicketStore, initialTickets } from "../composables/useTicketStore";
import { writeLS, LS_TICKETS } from "../utils/localStorage";
import { clearSession } from "../utils/session";
import Navbar from "../components/Navbar.vue";
import Modal from "../components/Modal.vue"; 
import TicketForm from "../components/TicketForm.vue";
import TicketList from "../components/TicketList.vue";

const toast = useToast();
const { tickets, createTicket, updateTicket, deleteTicket } = useTicketStore();
const router = useRouter();

const editing = ref(null);
const showModal = ref(false);
const query = ref("");
const filterStatus = ref("all");
const confirmDeleteId = ref(null);

const onCreate = (payload) => {
    createTicket(payload);
    toast.success("Ticket created!");
};
const onUpdate = (id, payload) => {
    updateTicket(id, payload);
    toast.success("Ticket updated!");
};
const requestDelete = (id) => confirmDeleteId.value = id;
const cancelDelete = () => confirmDeleteId.value = null;
const confirmDelete = () => {
  if (confirmDeleteId.value) {
    deleteTicket(confirmDeleteId.value);
    confirmDeleteId.value = null;
    toast.success("Ticket deleted.");
  }
};

const logoutAndNavigate = () => {
    clearSession();
    router.replace("/");
    toast.success("Logged out successfully.");
};

const filtered = computed(() => {
  let list = tickets.value;
  if (filterStatus.value !== "all") {
    list = list.filter((t) => t.status === filterStatus.value);
  }
  if (query.value.trim()) {
    const q = query.value.trim().toLowerCase();
    list = list.filter(
      (t) => t.title.toLowerCase().includes(q) || t.description.toLowerCase().includes(q)
    );
  }
  return list;
});

const openEditModal = (ticket) => {
    editing.value = ticket;
    showModal.value = true;
};

const handleModalFormSubmit = (data) => {
    if (editing.value) {
        onUpdate(editing.value.id, data);
    } else {
        onCreate(data);
    }
    showModal.value = false;
    editing.value = null;
};

const handleModalCancel = () => {
    showModal.value = false;
    editing.value = null;
};

const resetSampleData = () => {
    if (window.confirm("Reset tickets to demo data?")) {
        writeLS(LS_TICKETS, initialTickets);
        window.location.reload();
    }
};

const exportTickets = () => {
    const dataStr = JSON.stringify(tickets.value, null, 2);
    const blob = new Blob([dataStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "tickets.json";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Export started");
};

</script>

<template>
  <div class="page-wrap">
    <Navbar @logout="logoutAndNavigate" />
    <div class="container">
      <div class="page-header">
        <div class="header-info">
          <h1>{{ editing ? "Edit Ticket" : "Tickets" }}</h1>
          <p>{{ editing ? "Editing mode" : "Create and manage tickets" }}</p>
        </div>
        <div class="search-filter-group">
          <input
            class="search-input input"
            aria-label="Search tickets"
            placeholder="Search tickets..."
            v-model="query"
          />
          <select class="status-select select" aria-label="Filter status" v-model="filterStatus">
            <option value="all">All statuses</option>
            <option value="open">Open</option>
            <option value="in_progress">In Progress</option>
            <option value="closed">Closed</option>
          </select>
          <button class="primary-button" @click="() => { editing = null; showModal = true; }" aria-label="Create new ticket">New Ticket</button>
        </div>
      </div>

      <div class="grid-layout">
        <div>
          <section class="card">
            <h3 style="margin-top: 0">All Tickets</h3>
            <TicketList
              :tickets="filtered"
              :onEdit="openEditModal"
              :onDelete="requestDelete"
              :onOpen="(id) => router.push(`/tickets/${id}`)"
            />
          </section>
        </div>

        <div>
          <section class="card">
            <h3 style="margin-top: 0">{{ editing ? "Edit Ticket" : "Create Ticket" }}</h3>
            <TicketForm
              :initial="editing"
              :onSubmit="(data) => {
                  if (editing) onUpdate(editing.id, data);
                  else onCreate(data);
                  editing = null;
              }"
              :onCancel="() => editing = null"
            />
          </section>

          <div class="spacer"></div>

          <section class="card">
            <h4 style="margin-top: 0">Quick Actions</h4>
            <div class="quick-actions">
              <button class="primary-button" @click="resetSampleData">Reset sample data</button>
              <button class="nav-button" @click="exportTickets">Export</button>
            </div>
          </section>
        </div>
      </div>
    </div>

    <Modal :is-open="showModal" @close="handleModalCancel" :aria-label="editing ? 'Edit ticket' : 'Create ticket'">
      <h3 style="margin-top: 0">{{ editing ? "Edit Ticket" : "New Ticket" }}</h3>
      <TicketForm
        :initial="editing"
        :onSubmit="handleModalFormSubmit"
        :onCancel="handleModalCancel"
      />
    </Modal>

    <Modal :is-open="!!confirmDeleteId" @close="cancelDelete" aria-label="Confirm delete">
      <h3 style="margin-top: 0">Confirm delete</h3>
      <p>Are you sure you want to delete this ticket? This action cannot be undone.</p>
      <div class="button-row">
        <button class="primary-button" @click="confirmDelete" aria-label="Confirm delete">Yes, delete</button>
        <button class="nav-button" @click="cancelDelete" aria-label="Cancel delete">Cancel</button>
      </div>
    </Modal>

    <footer class="footer-wrap">{{ new Date().getFullYear() }} Ticketi•fy — © UnSiMplYkells</footer>
  </div>
</template>

<style scoped>

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 18px;
}

@media (max-width: 768px) {
  .page-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 12px;
  }
}

.header-info h1 {
  margin: 0;
  font-size: 20px;
  color: var(--color-text);
}
.header-info p {
  margin: 6px 0 0;
  color: var(--color-mutted);
  font-size: 14px;
}

.search-filter-group {
  display: flex;
  gap: 8px;
}

@media (max-width: 768px) {
  .search-filter-group {
    flex-wrap: wrap;
    width: 100%;
  }
}

.search-input {
  width: 220px;
}

@media (max-width: 768px) {
  .search-input {
    width: 100%;
  }
}

.status-select {
  width: 160px;
}

@media (max-width: 768px) {
  .status-select {
    width: 100%;
  }
}

.grid-layout {
  display: grid;
  grid-template-columns: 1fr 420px;
  gap: 16px;
  margin-top: 18px;
}

@media (max-width: 1024px) {
  .grid-layout {
    grid-template-columns: 1fr 1fr;
  }
}

@media (max-width: 768px) {
  .grid-layout {
    grid-template-columns: 1fr;
  }
}

.quick-actions {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.spacer {
  height: 12px;
}

.button-row {
  display: flex;
  gap: 8px;
  margin-top: 16px;
}

@media (max-width: 480px) {
  .button-row {
    flex-direction: column;
  }
}
</style>

// stage 2/react implementation/src/pages/TicketsPage.jsx
import { useState, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-hot-toast";
import styled from "styled-components";
import {
  PageWrap,
  Container,
  Card,
  Input,
  Select,
  PrimaryButton,
  NavButton,
  FooterWrap,
  Avatar,
  Badge,
  Small,
  InlineLink
} from "../styles/styledBits";
import { Navbar } from "../components/Navbar";
import { Modal } from "../components/Modal";
import { TicketForm } from "./TicketForm";
import { initialTickets } from "../hooks/useTicketStore";
import { writeLS } from "../utils/localStorage";
import { clearSession } from "../utils/session";

const ListWrapper = styled.ul`
  list-style: none;
  padding: 0;
  margin: 0;
`;

const ListItem = styled.li`
  display: flex;
  justify-content: space-between;
  gap: 12px;
  padding: 14px;
  border-bottom: 1px solid #f1f5f9;
  align-items: center;

  @media (max-width: 600px) {
    flex-direction: column;
    align-items: flex-start;
  }
`;

const ItemLeft = styled.div`
  display: flex;
  gap: 12px;
  align-items: center;

  @media (max-width: 600px) {
    margin-bottom: 8px;
  }
`;

const ItemRight = styled.div`
  display: flex;
  gap: 8px;
  align-items: center;

  @media (max-width: 600px) {
    flex-wrap: wrap;
  }
`;

const ActionsGroup = styled.div`
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
`;

const PageHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 18px;

  @media (max-width: 768px) {
    flex-direction: column;
    align-items: flex-start;
    gap: 12px;
  }
`;

const HeaderInfo = styled.div`
  h1 {
    margin: 0;
    font-size: 20px;
    color: #0f172a;
  }
  p {
    margin: 6px 0 0;
    color: #6b7280;
    font-size: 14px;
  }
`;

const SearchFilterGroup = styled.div`
  display: flex;
  gap: 8px;

  @media (max-width: 768px) {
    flex-wrap: wrap;
    width: 100%;
  }
`;

const SearchInput = styled(Input)`
  width: 220px;

  @media (max-width: 768px) {
    width: 100%;
  }
`;

const StatusSelect = styled(Select)`
  width: 160px;

  @media (max-width: 768px) {
    width: 100%;
  }
`;

const GridLayout = styled.div`
  display: grid;
  grid-template-columns: 1fr 420px;
  gap: 16px;
  margin-top: 18px;

  @media (max-width: 1024px) {
    grid-template-columns: 1fr 1fr;
  }

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
  }
`;

const QuickActions = styled.div`
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
`;

const Spacer = styled.div`
  height: 12px;
`;

const ButtonRow = styled.div`
  display: flex;
  gap: 8px;
  margin-top: 16px;

  @media (max-width: 480px) {
    flex-direction: column;
  }
`;

export const TicketList = ({ tickets = [], onEdit, onDelete, onOpen }) => {
  if (!tickets || tickets.length === 0) return <p>No tickets yet</p>;

  return (
    <ListWrapper>
      {tickets.map((ticket) => (
        <ListItem key={ticket.id}>
          <ItemLeft>
            <Avatar aria-hidden>{ticket.title.charAt(0)}</Avatar>
            <div>
              <div style={{ fontWeight: 700 }}>{ticket.title}</div>
              <Small>{ticket.description}</Small>
            </div>
          </ItemLeft>

          <ItemRight>
            <Badge variant={ticket.status} role="status" aria-label={`status ${ticket.status}`}>
              {ticket.status === "open"
                ? "Open"
                : ticket.status === "in_progress"
                ? "In Progress"
                : "Closed"}
            </Badge>
            <Small>{ticket.priority}</Small>
            <ActionsGroup>
              {onOpen && <InlineLink aria-label={`View ${ticket.title}`} onClick={() => onOpen(ticket.id)}>View</InlineLink>}
              {onEdit && <InlineLink aria-label={`Edit ${ticket.title}`} onClick={() => onEdit(ticket)}>Edit</InlineLink>}
              {onDelete && <InlineLink aria-label={`Delete ${ticket.title}`} onClick={() => onDelete(ticket.id)} style={{ color: "#dc2626" }}>Delete</InlineLink>}
            </ActionsGroup>
          </ItemRight>
        </ListItem>
      ))}
    </ListWrapper>
  );
};

// Tickets Page Component
export const TicketsPage = ({ ticketStore }) => {
  const { tickets, createTicket, updateTicket, deleteTicket } = ticketStore;
  const [editing, setEditing] = useState(null);
  const [showModal, setShowModal] = useState(false);
  const [query, setQuery] = useState("");
  const [filterStatus, setFilterStatus] = useState("all");
  const [confirmDeleteId, setConfirmDeleteId] = useState(null);
  const navigate = useNavigate();

  const onCreate = (payload) => createTicket(payload);
  const onUpdate = (id, payload) => updateTicket(id, payload);
  const requestDelete = (id) => setConfirmDeleteId(id);
  const confirmDelete = () => {
    if (confirmDeleteId) {
      deleteTicket(confirmDeleteId);
      setConfirmDeleteId(null);
    }
  };
  const cancelDelete = () => setConfirmDeleteId(null);

  const filtered = useMemo(() => {
    let list = tickets;
    if (filterStatus !== "all") list = list.filter((t) => t.status === filterStatus);
    if (query.trim()) {
      const q = query.trim().toLowerCase();
      list = list.filter(
        (t) => t.title.toLowerCase().includes(q) || t.description.toLowerCase().includes(q)
      );
    }
    return list;
  }, [tickets, query, filterStatus]);

  const handleLogout = () => {
    clearSession();
    window.location.href = "/";
  };

  return (
    <PageWrap>
      <Navbar onLogout={handleLogout} />
      <Container>
        <PageHeader>
          <HeaderInfo>
            <h1>{editing ? "Edit Ticket" : "Tickets"}</h1>
            <p>{editing ? "Editing mode" : "Create and manage tickets"}</p>
          </HeaderInfo>
          <SearchFilterGroup>
            <SearchInput aria-label="Search tickets" placeholder="Search tickets..." value={query} onChange={(e) => setQuery(e.target.value)} />
            <StatusSelect aria-label="Filter status" value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)}>
              <option value="all">All statuses</option>
              <option value="open">Open</option>
              <option value="in_progress">In Progress</option>
              <option value="closed">Closed</option>
            </StatusSelect>
            <PrimaryButton onClick={() => { setEditing(null); setShowModal(true); }} aria-label="Create new ticket">New Ticket</PrimaryButton>
          </SearchFilterGroup>
        </PageHeader>

        <GridLayout>
          <div>
            <Card>
              <h3 style={{ marginTop: 0 }}>All Tickets</h3>
              <TicketList
                tickets={filtered}
                onEdit={(t) => { setEditing(t); setShowModal(true); }}
                onDelete={(id) => requestDelete(id)}
                onOpen={(id) => navigate(`/tickets/${id}`)}
              />
            </Card>
          </div>

          <div>
            <Card>
              <h3 style={{ marginTop: 0 }}>{editing ? "Edit Ticket" : "Create Ticket"}</h3>
              <TicketForm
                key={editing ? editing.id : "new"}
                initial={editing || null}
                onSubmit={(data) => {
                  if (editing) {
                    onUpdate(editing.id, data);
                    setEditing(null);
                  } else {
                    onCreate(data);
                  }
                }}
                onCancel={() => setEditing(null)}
              />
            </Card>

            <Spacer />

            <Card>
              <h4 style={{ marginTop: 0 }}>Quick Actions</h4>
              <QuickActions>
                <PrimaryButton onClick={() => {
                  if (window.confirm("Reset tickets to demo data?")) {
                    writeLS("ticketflow::tickets_v1", initialTickets);
                    window.location.reload();
                  }
                }}>Reset sample data</PrimaryButton>

                <NavButton onClick={() => {
                  const dataStr = JSON.stringify(tickets, null, 2);
                  const blob = new Blob([dataStr], { type: "application/json" });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement("a");
                  a.href = url;
                  a.download = "tickets.json";
                  a.click();
                  URL.revokeObjectURL(url);
                  toast.success("Export started");
                }}>Export</NavButton>
              </QuickActions>
            </Card>
          </div>
        </GridLayout>
      </Container>

      <Modal isOpen={showModal} onClose={() => { setShowModal(false); setEditing(null); }} ariaLabel={editing ? "Edit ticket" : "Create ticket"}>
        <h3 style={{ marginTop: 0 }}>{editing ? "Edit Ticket" : "New Ticket"}</h3>
        <TicketForm
          initial={editing || null}
          onSubmit={(data) => {
            if (editing) onUpdate(editing.id, data);
            else onCreate(data);
            setShowModal(false);
            setEditing(null);
          }}
          onCancel={() => { setShowModal(false); setEditing(null); }}
        />
      </Modal>

      <Modal isOpen={!!confirmDeleteId} onClose={() => setConfirmDeleteId(null)} ariaLabel="Confirm delete">
        <h3 style={{ marginTop: 0 }}>Confirm delete</h3>
        <p>Are you sure you want to delete this ticket? This action cannot be undone.</p>
        <ButtonRow>
          <PrimaryButton onClick={confirmDelete} aria-label="Confirm delete">Yes, delete</PrimaryButton>
          <NavButton onClick={cancelDelete} aria-label="Cancel delete">Cancel</NavButton>
        </ButtonRow>
      </Modal>

      <FooterWrap>{new Date().getFullYear()} Ticketi•fy — © UnSiMplYkells</FooterWrap>
    </PageWrap>
  );
};
