// vue implementaion/src/pages/auth/SignupPage.vue
<script setup>
import { ref, onMounted } from "vue";
import { useRouter, RouterLink } from "vue-router";
import { useToast } from "vue-toastification";
import { useAuthStore } from "../../composables/useAuthStore";
import { isAuthenticated } from "../../utils/session";
import Navbar from "../../components/Navbar.vue";

const toast = useToast();
const router = useRouter();
const auth = useAuthStore();
const email = ref("");
const password = ref("");
const error = ref("");
const submitting = ref(false);

onMounted(() => {
  if (isAuthenticated()) router.replace("/dashboard");
});

const validateEmail = (em) => /\S+@\S+\.\S+/.test(em);

const handleSubmit = (e) => {
  e.preventDefault();
  error.value = "";

  if (!email.value || !password.value) {
    error.value = "Please fill in all fields";
    return;
  }

  if (!validateEmail(email.value)) {
    error.value = "Please enter a valid email address";
    return;
  }

  if (password.value.length < 6) {
    error.value = "Password must be at least 6 characters";
    toast.error("Password must be at least 6 characters");
    return;
  }

  submitting.value = true;
  setTimeout(() => {
    const res = auth.signup(email.value.trim(), password.value);
    if (res.ok) {
      toast.success("Account created");
      router.push("/dashboard");
    } else {
      error.value = res.message || "Could not create account";
      toast.error(res.message || "Could not create account");
    }
    submitting.value = false;
  }, 300);
};
</script>

<template>
  <div class="page-wrap">
    <Navbar />
    <div class="container" style="padding: 48px;">
      <div class="centered-wrapper">
        <section class="styled-card card">
          <h1 class="styled-title title">Create a new account</h1>
          <p class="styled-subtle subtle">Create your account to get started.</p>

          <form @submit="handleSubmit">
            <div class="form-row">
              <label class="label">Email address</label>
              <input
                class="input"
                aria-label="Email address"
                v-model="email"
                type="email"
                required
              />
            </div>

            <div class="form-row">
              <label class="label">Password</label>
              <input
                class="input"
                aria-label="Password"
                v-model="password"
                type="password"
                required
              />
            </div>

            <div v-if="error" class="error-message">{{ error }}</div>

            <div class="submit-row form-row">
              <button
                type="submit"
                class="primary-button"
                :disabled="submitting"
                :aria-disabled="submitting"
              >
                {{ submitting ? "Please wait..." : "Sign up" }}
              </button>
            </div>
          </form>

          <p class="bottom-text">
            Already have an account? <RouterLink to="/auth/login" class="bottom-link">Sign in</RouterLink>
          </p>
        </section>
      </div>
    </div>

    <footer class="footer-wrap">© {{ new Date().getFullYear() }} Ticketi•fy — © UnSiMplYkells</footer>
  </div>
</template>

<style scoped>
.centered-wrapper {
  display: flex;
  justify-content: center;
  margin-top: 42px;
}

.styled-card {
  width: 520px;
}

.styled-title {
  margin-bottom: 6px;
}

.styled-subtle {
  margin-bottom: 12px;
}

.error-message {
  margin-top: 12px;
  color: var(--color-danger);
  font-size: 13px;
}

.submit-row {
  margin-top: 18px;
}

.bottom-text {
  margin: 12px 0 0 0;
  font-size: 13px;
  color: #6b7280;
}

.bottom-link {
  color: #2563eb;
  font-weight: 600;
  text-decoration: none;
}

.bottom-link:hover {
  text-decoration: underline;
}
</style>

// react implementation/src/pages/auth/SignupPage.jsx
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-hot-toast";
import styled from "styled-components";
import { PageWrap, Container, Card, Title, Subtle, FormRow, Label, Input, PrimaryButton, FooterWrap } from "../../styles/styledBits";
import { Navbar } from "../../components/Navbar";
import { useAuthStore } from "../../hooks/useAuthStore";
import { isAuthenticated } from "../../utils/session";

const CenteredWrapper = styled.div`
  display: flex;
  justify-content: center;
  margin-top: 42px;
`;

const StyledCard = styled(Card)`
  width: 520px;
`;

const StyledTitle = styled(Title)`
  margin-bottom: 6px;
`;

const StyledSubtle = styled(Subtle)`
  margin-bottom: 12px;
`;

const ErrorMessage = styled.div`
  margin-top: 12px;
  color: #dc2626;
  font-size: 13px;
`;

const SubmitRow = styled(FormRow)`
  margin-top: 18px;
`;

const BottomText = styled.p`
  margin: 12px 0 0 0;
  font-size: 13px;
  color: #6b7280;
`;

const BottomLink = styled.a`
  color: #2563eb;
  font-weight: 600;
  text-decoration: none;

  &:hover {
    text-decoration: underline;
  }
`;

export const SignupPage = () => {
  const navigate = useNavigate();
  const auth = useAuthStore();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (isAuthenticated()) navigate("/dashboard", { replace: true });
  }, [navigate]);

  const validateEmail = (em) => /\S+@\S+\.\S+/.test(em);

  const handleSubmit = (e) => {
    e.preventDefault();
    setError("");

    if (!email || !password) {
      setError("Please fill in all fields");
      return;
    }

    if (!validateEmail(email)) {
      setError("Please enter a valid email address");
      return;
    }

    if (password.length < 6) {
      setError("Password must be at least 6 characters");
      toast.error("Password must be at least 6 characters");
      return;
    }

    setSubmitting(true);
    setTimeout(() => {
      const res = auth.signup(email.trim(), password);
      if (res.ok) {
        toast.success("Account created");
        navigate("/dashboard");
      } else {
        setError(res.message || "Could not create account");
        toast.error(res.message || "Could not create account");
      }
      setSubmitting(false);
    }, 300);
  };

  return (
    <PageWrap>
      <Navbar />
      <Container px="48px">
        <CenteredWrapper>
          <StyledCard>
            <StyledTitle>Create a new account</StyledTitle>
            <StyledSubtle>Create your account to get started.</StyledSubtle>

            <form onSubmit={handleSubmit}>
              <FormRow>
                <Label>Email address</Label>
                <Input
                  aria-label="Email address"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  type="email"
                  required
                />
              </FormRow>

              <FormRow>
                <Label>Password</Label>
                <Input
                  aria-label="Password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  type="password"
                  required
                />
              </FormRow>

              {error && <ErrorMessage>{error}</ErrorMessage>}

              <SubmitRow>
                <PrimaryButton type="submit" disabled={submitting} aria-disabled={submitting}>
                  {submitting ? "Please wait..." : "Sign up"}
                </PrimaryButton>
              </SubmitRow>
            </form>

            <BottomText>
              Already have an account? <BottomLink href="/auth/login">Sign in</BottomLink>
            </BottomText>
          </StyledCard>
        </CenteredWrapper>
      </Container>

      <FooterWrap>© {new Date().getFullYear()} Ticketi•fy — © UnSiMplYkells</FooterWrap>
    </PageWrap>
  );
};
